services:
  foodtech_worker:
    build: .
    ports:
      - "8081:8081"
    environment:
      # spring.application.name -> SPRING_APPLICATION_NAME
      SPRING_APPLICATION_NAME: foodtech_worker
      # server.port -> SERVER_PORT
      SERVER_PORT: 8081

      # Datasource settings
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/foodtech_db
      SPRING_DATASOURCE_USERNAME: foodtech_user
      SPRING_DATASOURCE_PASSWORD: foodtech_pass

      # JPA / Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      # RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      FOODTECH_RABBITMQ_QUEUE: foodtech.queue
      FOODTECH_RABBITMQ_EXCHANGE: foodtech.exchange
      FOODTECH_RABBITMQ_ROUTINGKEY: foodtech.routingkey

      # Outbox
      FOODTECH_OUTBOX_MAX_ATTEMPTS: "10"
      FOODTECH_OUTBOX_SCHEDULER_RATE: "10000"

      # Logging
      LOGGING_LEVEL_COM_FOODTECH_KITCHEN_WORKER_FOODTECH_WORKER_INFRASTRUCTURE_ADAPTERS_INPUT_SCHEDULER: DEBUG

      # Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: ms-factura-group
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
      SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
      SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
      SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: '*'

      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
      SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS: "false"

      # Message broker strategy
      FOODTECH_MESSAGE_BROKER: kafka

      # Topic
      FOODTECH_KAFKA_TOPIC: foodtech.factura.created
    networks: [foodtech-net]

networks:
  foodtech-net:
    external: true
    name: foodtech-net